### ISSUE TITLE
1.0 stabilization tracker

### ISSUE THREAD

**Issue by arnetheduck** [arnetheduck/nim-results#30]
* [ ] Decide what to do with "experimental" API - ie enable-by-default, post-deprecation-warning, etc
* [ ] document API stability guarantees in general
* [ ] document Nim version support policy
* [ ] drop 1.2?
* [ ] deprecate in stew - chicken/egg problem (since stew per definition is a work-in-progress repo)

**Comment by tersec** [comment]
I'd say drop 1.2, unsurprisingly. No legacy users, no reason to start supporting it now.

**Comment by arnetheduck** [comment]
* [ ] create a sustainability / long-term maintenance plan
