### ISSUE TITLE
out of date tracked issues

### ISSUE THREAD

**Issue by bung87** [arnetheduck/nim-results#33]
- [ ] https://github.com/nim-lang/Nim/issues/20699 one attempt to fix but reverted
- [x] https://github.com/nim-lang/Nim/issues/3770
- [x] https://github.com/nim-lang/Nim/issues/20900
- [ ] https://github.com/nim-lang/Nim/issues/13799 - type issues
- [x] https://github.com/nim-lang/Nim/issues/8745 - genericReset slow
- [x] https://github.com/nim-lang/Nim/issues/13879 - double-zero-init slow
- [x] https://github.com/nim-lang/Nim/issues/14318 - generic error raises pragma
